version: '3'
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "3000:3000"
        networks:
            - cpray-net
            - bridge
    redis:
        image: redislabs/rejson:latest
        ports:
            - "6379:6379"
        networks:
            - cpray-net